openapi: 3.0.0
info:
  title: Order Management API
  version: 1.0.0
  description: API for updating orders.

paths:
  /users/orders/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      summary: Update Order
      description: Update the details of a specific order.
      requestBody:
        description: Order object with updated details.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        '200':
          description: Order updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found.
        '400':
          description: Bad request.
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the order.
        order_status_id:
          type: integer
          description: The status identifier of the order.
        user_id:
          type: integer
          description: The user who placed the order.
        amount:
          type: integer
          description: The total amount for the order.
        tracking_id:
          type: string
          description: Unique tracking identifier for the order.
        created_at:
          type: string
          format: date-time
          description: The timestamp when the order was created.
        updated_at:
          type: string
          format: date-time
          description: The timestamp when the order was last updated.
