openapi: 3.0.0
info:
  title: Order Management API
  version: 1.0.0
  description: API for retrieving orders and their counts.

paths:
  /users/orders:
    get:
      summary: Get Orders
      description: Retrieve a list of orders for a user along with the total count of all orders and active orders.
      responses:
        '200':
          description: A list of orders with counts.
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_orders:
                    type: integer
                    description: The total count of all orders.
                  active_orders:
                    type: integer
                    description: The count of active orders.
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the order.
        order_status_id:
          type: integer
          description: The status identifier of the order.
        user_id:
          type: integer
          description: The user who placed the order.
        amount:
          type: integer
          description: The total amount for the order.
        tracking_id:
          type: string
          description: Unique tracking identifier for the order.
        created_at:
          type: string
          format: date-time
          description: The timestamp when the order was created.
        updated_at:
          type: string
          format: date-time
          description: The timestamp when the order was last updated.
    OrderCounts:
      type: object
      properties:
        total_orders:
          type: integer
          description: The total count of all orders.
        active_orders:
          type: integer
          description: The count of active orders.
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
